/**
 * Tests for CSV parsing and reservation-status helpers.
 *
 * The CSV pipeline has high blast radius (every monthly import flows
 * through it) but had no tests. These cover the parse-time behavior:
 * header detection with preamble lines, column-mapping flexibility,
 * required-field enforcement, gender normalization, and status filtering
 * that downstream code uses to split active vs cancelled vs other.
 */

import { describe, it, expect } from 'vitest'
import { useCSV } from './useCSV'
import {
  isActiveReservationStatus,
  isCancelledStatus,
  NON_ASSIGNABLE_HOUSING_TYPES,
} from '@/types'

// crypto.randomUUID() is not always present under jsdom — provide a stub
// so parseGuestCSV's id assignment doesn't throw in the test runner.
if (typeof globalThis.crypto === 'undefined') {
  ;(globalThis as { crypto: Crypto }).crypto = {
    randomUUID: () => Math.random().toString(36).slice(2) as `${string}-${string}-${string}-${string}-${string}`,
  } as Crypto
} else if (typeof globalThis.crypto.randomUUID !== 'function') {
  globalThis.crypto.randomUUID = () =>
    Math.random().toString(36).slice(2) as `${string}-${string}-${string}-${string}-${string}`
}

const HEADER_BASIC = 'First Name,Last Name,Gender,Age'

describe('parseGuestCSV', () => {
  it('parses a minimal valid CSV', () => {
    const { parseGuestCSV } = useCSV()
    const csv = `${HEADER_BASIC}\nAlice,Smith,F,40\nBob,Jones,M,42`
    const result = parseGuestCSV(csv)

    expect(result.guests).toHaveLength(2)
    expect(result.guests[0].firstName).toBe('Alice')
    expect(result.guests[0].lastName).toBe('Smith')
    expect(result.guests[0].gender).toBe('F')
    expect(result.guests[0].age).toBe(40)
    expect(result.guests[1].firstName).toBe('Bob')
    expect(result.guests[1].gender).toBe('M')
    expect(result.totalRows).toBe(2)
  })

  it('skips Planyo-style preamble lines and finds the real header', () => {
    const { parseGuestCSV } = useCSV()
    const csv = [
      'Reservations From: Feb 13, 2026 To: Feb 13, 2026',
      'Generated by Planyo',
      '',
      HEADER_BASIC,
      'Alice,Smith,F,40',
    ].join('\n')

    const result = parseGuestCSV(csv)
    expect(result.guests).toHaveLength(1)
    expect(result.guests[0].firstName).toBe('Alice')
  })

  it('throws when no header row is recognizable', () => {
    const { parseGuestCSV } = useCSV()
    const csv = 'foo,bar,baz\n1,2,3'

    expect(() => parseGuestCSV(csv)).toThrow(/Could not find a header row/)
  })

  it('throws when required columns are missing', () => {
    const { parseGuestCSV } = useCSV()
    // Has only First Name + Age; missing Last Name and Gender
    const csv = 'First Name,Age\nAlice,40'

    expect(() => parseGuestCSV(csv)).toThrow(/Missing required columns/)
  })

  it('accepts the column-name variations from CSV_FIELD_MAPPINGS', () => {
    const { parseGuestCSV } = useCSV()
    // Mix uppercase, snake_case, and Planyo's "ID" / "Status"
    const csv = [
      'FIRST NAME,LAST NAME,GENDER,AGE,Group Name,Reservation ID,Status',
      'Alice,Smith,F,40,Smith Family,RES-001,Reserved',
    ].join('\n')

    const result = parseGuestCSV(csv)
    expect(result.guests).toHaveLength(1)
    const g = result.guests[0]
    expect(g.firstName).toBe('Alice')
    expect(g.lastName).toBe('Smith')
    expect(g.gender).toBe('F')
    expect(g.age).toBe(40)
    expect(g.groupName).toBe('Smith Family')
    expect(g.planyoId).toBe('RES-001')
    expect(g.status).toBe('Reserved')
  })

  it('normalizes gender to M / F / Non-binary/Other', () => {
    const { parseGuestCSV } = useCSV()
    const csv = [
      HEADER_BASIC,
      'Alice,Smith,Male,40',
      'Bob,Jones,female,42',
      'Casey,Lee,Non-binary,30',
      'Dana,Park,nb,29',
    ].join('\n')

    const result = parseGuestCSV(csv)
    expect(result.guests.map(g => g.gender)).toEqual([
      'M',
      'F',
      'Non-binary/Other',
      'Non-binary/Other',
    ])
  })

  it('rejects rows with invalid gender and reports them in warnings', () => {
    const { parseGuestCSV } = useCSV()
    const csv = [
      HEADER_BASIC,
      'Alice,Smith,F,40',
      'Bob,Jones,Xyz,42',
    ].join('\n')

    const result = parseGuestCSV(csv)
    expect(result.guests).toHaveLength(1)
    expect(result.guests[0].firstName).toBe('Alice')
    expect(result.warnings.some(w => /Invalid gender/.test(w))).toBe(true)
  })

  it('rejects rows missing first or last name', () => {
    const { parseGuestCSV } = useCSV()
    const csv = [
      HEADER_BASIC,
      'Alice,Smith,F,40',
      ',Jones,M,42',
      'Casey,,F,30',
    ].join('\n')

    const result = parseGuestCSV(csv)
    expect(result.guests).toHaveLength(1)
    expect(result.warnings.length).toBe(2)
  })

  it('handles quoted fields with embedded commas', () => {
    const { parseGuestCSV } = useCSV()
    const csv = [
      'First Name,Last Name,Gender,Age,Notes',
      'Alice,Smith,F,40,"Loud, snores"',
    ].join('\n')

    const result = parseGuestCSV(csv)
    expect(result.guests[0].notes).toBe('Loud, snores')
  })

  it('strips trailing comma noise from housingType (Planyo CSV quirk)', () => {
    const { parseGuestCSV } = useCSV()
    const csv = [
      'First Name,Last Name,Gender,Age,Housing Type',
      'Alice,Smith,F,40,"Dorm,"',
    ].join('\n')

    const result = parseGuestCSV(csv)
    expect(result.guests[0].housingType).toBe('Dorm')
  })

  it('flags row-length mismatches as warnings without crashing', () => {
    const { parseGuestCSV } = useCSV()
    const csv = [
      HEADER_BASIC,
      'Alice,Smith,F,40',
      'Bob,Jones,M', // missing age column
    ].join('\n')

    const result = parseGuestCSV(csv)
    expect(result.guests).toHaveLength(1)
    expect(result.warnings.some(w => /Expected 4 columns/.test(w))).toBe(true)
  })
})

describe('isActiveReservationStatus', () => {
  it('treats missing/empty status as active (legacy / non-Planyo CSV)', () => {
    expect(isActiveReservationStatus(undefined)).toBe(true)
    expect(isActiveReservationStatus(null)).toBe(true)
    expect(isActiveReservationStatus('')).toBe(true)
  })

  it('accepts any status containing "reserved" (case-insensitive, trimmed)', () => {
    expect(isActiveReservationStatus('Reserved')).toBe(true)
    expect(isActiveReservationStatus(' RESERVED ')).toBe(true)
    expect(isActiveReservationStatus('Reserved + Email address verified')).toBe(true)
    expect(
      isActiveReservationStatus('Reserved + Email address verified + confirmed')
    ).toBe(true)
    expect(isActiveReservationStatus('Reserved (rebooked)')).toBe(true)
  })

  it('rejects cancellations even when "reserved" is also present', () => {
    // "cancel" takes precedence over "reserved" so a hybrid status
    // like "Reserved → Cancelled" is treated as a cancellation.
    expect(isActiveReservationStatus('Cancelled')).toBe(false)
    expect(isActiveReservationStatus('Cancelled by admin')).toBe(false)
    expect(isActiveReservationStatus('Reserved → Cancelled')).toBe(false)
    expect(isActiveReservationStatus('Reservation cancelled')).toBe(false)
  })

  it('rejects OTHER statuses (no "reserved", no "cancel")', () => {
    expect(isActiveReservationStatus('Not completed')).toBe(false)
    expect(isActiveReservationStatus('Pending payment')).toBe(false)
    expect(isActiveReservationStatus('Added to waiting list')).toBe(false)
  })
})

describe('isCancelledStatus', () => {
  it('returns false for missing status', () => {
    expect(isCancelledStatus(undefined)).toBe(false)
    expect(isCancelledStatus(null)).toBe(false)
    expect(isCancelledStatus('')).toBe(false)
  })

  it('matches the substring "cancel" case-insensitively', () => {
    expect(isCancelledStatus('Cancelled')).toBe(true)
    expect(isCancelledStatus('cancelled')).toBe(true)
    expect(isCancelledStatus('CANCELLATION REQUESTED')).toBe(true)
    expect(isCancelledStatus('Cancelled by admin')).toBe(true)
  })

  it('does not match other non-active statuses', () => {
    expect(isCancelledStatus('Reserved')).toBe(false)
    expect(isCancelledStatus('Not completed')).toBe(false)
    expect(isCancelledStatus('Pending')).toBe(false)
  })

  it('active and cancelled are mutually exclusive on real Planyo statuses', () => {
    const samples = [
      'Reserved',
      'Reserved + Email address verified',
      'Reserved + Email address verified + confirmed',
      'Cancelled',
      'Cancelled by admin',
      'Not completed',
      'Added to waiting list',
    ]
    for (const s of samples) {
      const active = isActiveReservationStatus(s)
      const cancelled = isCancelledStatus(s)
      expect(active && cancelled).toBe(false)
    }
  })
})

/**
 * Room column → Housing category derivation.
 *
 * The newer registration export leaves `Housing type` blank on any row
 * where the guest picked a specific spot in the `Room` column, so Room
 * is what tells us whether they need a bed at all. Before this, a
 * `CampingCouples` guest landed in the unassigned list demanding a dorm
 * bed, because a blank housingType reads as "assignable".
 */
describe('parseGuestCSV — Room column and derived Housing', () => {
  const HEADER_ROOM = 'First Name,Last Name,Gender,Age,Housing type,Room'

  function housingFor(room: string, housing = '') {
    const { parseGuestCSV } = useCSV()
    // Both values are quoted: Planyo's trailing commas ("Dorm,") would
    // otherwise split into an extra column.
    const csv = `${HEADER_ROOM}\nAlice,Smith,F,40,"${housing}","${room}"`
    return parseGuestCSV(csv).guests[0]
  }

  it('keeps the raw Room value on the guest', () => {
    const guest = housingFor('CrystalSunshine Rm 1 ( female only) - bed 7')
    expect(guest.roomRequest).toBe('CrystalSunshine Rm 1 ( female only) - bed 7')
  })

  it.each([
    ['CampingMen', 'Camping'],
    ['CampingWomen', 'Camping'], // appears in the v3 export
    ['CampingCouples', 'Camping'],
    ['Camping', 'Camping'],
  ])('maps %s to %s', (room, expected) => {
    expect(housingFor(room).housingType).toBe(expected)
  })

  it.each([
    ['Commuter', 'Commuter'],
    // Doubled-m misspelling seen in real registration data
    ['Commmuter', 'Commuter'],
  ])('maps %s to %s', (room, expected) => {
    expect(housingFor(room).housingType).toBe(expected)
  })

  it.each([
    ['Canvas Tent1-bed1', 'Canvas Tent'],
    ['Canvas Tent3-bed2', 'Canvas Tent'],
    ['CanvasTent1-bed1', 'Canvas Tent'],
  ])('maps %s to %s', (room, expected) => {
    expect(housingFor(room).housingType).toBe(expected)
  })

  it.each([
    // Real dorm rooms
    ['CrystalSunshine Rm 1 ( female only) - bed 7', 'Dorm'],
    ['CrystalSunshine Rm 2 ( female only) - bed 2L', 'Dorm'],
    ['FlameBlossom Rm 1 ( female only) - bed 6', 'Dorm'],
    // RV sites are Dorm by decision — they need a bed
    ['RV Daffodil-1', 'Dorm'],
    ['RV Daffodil-2', 'Dorm'],
    // v2-file shapes: no space before the dash, male-only and
    // mixed/group annotations, single/lower bed suffixes
    ['FlameBlossom Rm 00 ( female only)- bed 2S', 'Dorm'],
    ['HeavenlyMusic Rm 4 ( male only) - bed 1L', 'Dorm'],
    ['GoldenLotus Rm 00 (mixed/ group) - bed 1L', 'Dorm'],
    ['CrystalSunshine Rm 2 ( female only)- bed 6', 'Dorm'],
    // v3-file shapes: punctuation varies row to row because operators
    // type these by hand — no space before the paren, no space inside
    // it, no dash at all, a "couple" annotation, capitalized
    // "Mixed/ Group", and rooms with no gender annotation
    ['CrystalSunshine Rm 1( female only) - bed 1L', 'Dorm'],
    ['CrystalSunshine Rm 1 (female only) - bed 6', 'Dorm'],
    ['CrystalSunshine Rm 2 ( female only) bed 1L', 'Dorm'],
    ['RoseCloud Rm 1( couple ) - bed 1L', 'Dorm'],
    ['RoseCloud Rm 3 - bed 4', 'Dorm'],
    ['GoldenLotus Rm 4 (Mixed/ Group) - bed 1L', 'Dorm'],
    // A bare room name with no bed at all
    ['JADE CANDLE', 'Dorm'],
    // Catch-all: an unrecognized room still means "needs a bed", so the
    // guest stays visible in the unassigned list rather than vanishing
    ['Some Room Nobody Anticipated', 'Dorm'],
  ])('maps %s to %s', (room, expected) => {
    expect(housingFor(room).housingType).toBe(expected)
  })

  it('defaults to Dorm when both Housing and Room are blank', () => {
    expect(housingFor('', '').housingType).toBe('Dorm')
  })

  it('treats the Planyo "," artifact as blank, not as a category', () => {
    // Planyo exports an unset multi-select as a bare comma
    const { parseGuestCSV } = useCSV()
    const csv = `${HEADER_ROOM}\nAlice,Smith,F,40,",",CampingMen`
    expect(parseGuestCSV(csv).guests[0].housingType).toBe('Camping')
  })

  it('strips the trailing comma Planyo appends to a set value', () => {
    expect(housingFor('', 'Dorm,').housingType).toBe('Dorm')
  })

  // Planyo puts the empty slot's comma on whichever side wasn't filled,
  // so a leading comma is just as common as a trailing one. Missing it
  // left ",Camping" uncategorized — and therefore assignable.
  it('strips a LEADING comma Planyo prepends to a set value', () => {
    expect(housingFor('', ',Camping').housingType).toBe('Camping')
  })

  it('keeps a leading-comma Camping guest non-assignable', () => {
    const guest = housingFor('Canvas Tent2-bed1', ',Camping')
    expect(guest.housingType).toBe('Camping')
    expect(NON_ASSIGNABLE_HOUSING_TYPES).toContain(guest.housingType!.toLowerCase())
  })

  it('leaves a genuine two-value multi-select verbatim', () => {
    // Both slots set is ambiguous; don't guess, keep the guest visible
    expect(housingFor('', 'Dorm,Camping').housingType).toBe('Dorm,Camping')
  })

  it('lets a stated Housing win over a conflicting Room, and reports it', () => {
    const { parseGuestCSV } = useCSV()
    const csv = `${HEADER_ROOM}\nAlice,Smith,F,40,"Dorm,",CampingMen`
    const result = parseGuestCSV(csv)

    expect(result.guests[0].housingType).toBe('Dorm')
    expect(result.housingConflicts).toHaveLength(1)
    expect(result.housingConflicts[0]).toMatchObject({
      guestName: 'Alice Smith',
      roomRequest: 'CampingMen',
      stated: 'Dorm',
      impliedByRoom: 'Camping',
    })
  })

  it('reports no conflict when Housing and Room agree', () => {
    const { parseGuestCSV } = useCSV()
    const csv = `${HEADER_ROOM}\nAlice,Smith,F,40,"Camping,",CampingMen`
    const result = parseGuestCSV(csv)

    expect(result.guests[0].housingType).toBe('Camping')
    expect(result.housingConflicts).toHaveLength(0)
  })

  it('preserves a legacy Housing value it does not recognize', () => {
    // BCM-RV predates these categories and must round-trip untouched
    expect(housingFor('', 'BCM-RV').housingType).toBe('BCM-RV')
  })

  it('imports a CSV with no Room column at all, unchanged', () => {
    const { parseGuestCSV } = useCSV()
    const csv = `${HEADER_BASIC},Housing type\nAlice,Smith,F,40,"Dorm,"`
    const result = parseGuestCSV(csv)

    expect(result.guests).toHaveLength(1)
    expect(result.guests[0].housingType).toBe('Dorm')
    expect(result.guests[0].roomRequest).toBe('')
    expect(result.housingConflicts).toHaveLength(0)
  })
})
