/**
 * Tests for CSV parsing and reservation-status helpers.
 *
 * The CSV pipeline has high blast radius (every monthly import flows
 * through it) but had no tests. These cover the parse-time behavior:
 * header detection with preamble lines, column-mapping flexibility,
 * required-field enforcement, gender normalization, and status filtering
 * that downstream code uses to split active vs cancelled vs other.
 */

import { describe, it, expect } from 'vitest'
import { useCSV } from './useCSV'
import { isActiveReservationStatus, isCancelledStatus } from '@/types'

// crypto.randomUUID() is not always present under jsdom — provide a stub
// so parseGuestCSV's id assignment doesn't throw in the test runner.
if (typeof globalThis.crypto === 'undefined') {
  ;(globalThis as { crypto: Crypto }).crypto = {
    randomUUID: () => Math.random().toString(36).slice(2) as `${string}-${string}-${string}-${string}-${string}`,
  } as Crypto
} else if (typeof globalThis.crypto.randomUUID !== 'function') {
  globalThis.crypto.randomUUID = () =>
    Math.random().toString(36).slice(2) as `${string}-${string}-${string}-${string}-${string}`
}

const HEADER_BASIC = 'First Name,Last Name,Gender,Age'

describe('parseGuestCSV', () => {
  it('parses a minimal valid CSV', () => {
    const { parseGuestCSV } = useCSV()
    const csv = `${HEADER_BASIC}\nAlice,Smith,F,40\nBob,Jones,M,42`
    const result = parseGuestCSV(csv)

    expect(result.guests).toHaveLength(2)
    expect(result.guests[0].firstName).toBe('Alice')
    expect(result.guests[0].lastName).toBe('Smith')
    expect(result.guests[0].gender).toBe('F')
    expect(result.guests[0].age).toBe(40)
    expect(result.guests[1].firstName).toBe('Bob')
    expect(result.guests[1].gender).toBe('M')
    expect(result.totalRows).toBe(2)
  })

  it('skips Planyo-style preamble lines and finds the real header', () => {
    const { parseGuestCSV } = useCSV()
    const csv = [
      'Reservations From: Feb 13, 2026 To: Feb 13, 2026',
      'Generated by Planyo',
      '',
      HEADER_BASIC,
      'Alice,Smith,F,40',
    ].join('\n')

    const result = parseGuestCSV(csv)
    expect(result.guests).toHaveLength(1)
    expect(result.guests[0].firstName).toBe('Alice')
  })

  it('throws when no header row is recognizable', () => {
    const { parseGuestCSV } = useCSV()
    const csv = 'foo,bar,baz\n1,2,3'

    expect(() => parseGuestCSV(csv)).toThrow(/Could not find a header row/)
  })

  it('throws when required columns are missing', () => {
    const { parseGuestCSV } = useCSV()
    // Has only First Name + Age; missing Last Name and Gender
    const csv = 'First Name,Age\nAlice,40'

    expect(() => parseGuestCSV(csv)).toThrow(/Missing required columns/)
  })

  it('accepts the column-name variations from CSV_FIELD_MAPPINGS', () => {
    const { parseGuestCSV } = useCSV()
    // Mix uppercase, snake_case, and Planyo's "ID" / "Status"
    const csv = [
      'FIRST NAME,LAST NAME,GENDER,AGE,Group Name,Reservation ID,Status',
      'Alice,Smith,F,40,Smith Family,RES-001,Reserved',
    ].join('\n')

    const result = parseGuestCSV(csv)
    expect(result.guests).toHaveLength(1)
    const g = result.guests[0]
    expect(g.firstName).toBe('Alice')
    expect(g.lastName).toBe('Smith')
    expect(g.gender).toBe('F')
    expect(g.age).toBe(40)
    expect(g.groupName).toBe('Smith Family')
    expect(g.planyoId).toBe('RES-001')
    expect(g.status).toBe('Reserved')
  })

  it('normalizes gender to M / F / Non-binary/Other', () => {
    const { parseGuestCSV } = useCSV()
    const csv = [
      HEADER_BASIC,
      'Alice,Smith,Male,40',
      'Bob,Jones,female,42',
      'Casey,Lee,Non-binary,30',
      'Dana,Park,nb,29',
    ].join('\n')

    const result = parseGuestCSV(csv)
    expect(result.guests.map(g => g.gender)).toEqual([
      'M',
      'F',
      'Non-binary/Other',
      'Non-binary/Other',
    ])
  })

  it('rejects rows with invalid gender and reports them in warnings', () => {
    const { parseGuestCSV } = useCSV()
    const csv = [
      HEADER_BASIC,
      'Alice,Smith,F,40',
      'Bob,Jones,Xyz,42',
    ].join('\n')

    const result = parseGuestCSV(csv)
    expect(result.guests).toHaveLength(1)
    expect(result.guests[0].firstName).toBe('Alice')
    expect(result.warnings.some(w => /Invalid gender/.test(w))).toBe(true)
  })

  it('rejects rows missing first or last name', () => {
    const { parseGuestCSV } = useCSV()
    const csv = [
      HEADER_BASIC,
      'Alice,Smith,F,40',
      ',Jones,M,42',
      'Casey,,F,30',
    ].join('\n')

    const result = parseGuestCSV(csv)
    expect(result.guests).toHaveLength(1)
    expect(result.warnings.length).toBe(2)
  })

  it('handles quoted fields with embedded commas', () => {
    const { parseGuestCSV } = useCSV()
    const csv = [
      'First Name,Last Name,Gender,Age,Notes',
      'Alice,Smith,F,40,"Loud, snores"',
    ].join('\n')

    const result = parseGuestCSV(csv)
    expect(result.guests[0].notes).toBe('Loud, snores')
  })

  it('strips trailing comma noise from housingType (Planyo CSV quirk)', () => {
    const { parseGuestCSV } = useCSV()
    const csv = [
      'First Name,Last Name,Gender,Age,Housing Type',
      'Alice,Smith,F,40,"Dorm,"',
    ].join('\n')

    const result = parseGuestCSV(csv)
    expect(result.guests[0].housingType).toBe('Dorm')
  })

  it('flags row-length mismatches as warnings without crashing', () => {
    const { parseGuestCSV } = useCSV()
    const csv = [
      HEADER_BASIC,
      'Alice,Smith,F,40',
      'Bob,Jones,M', // missing age column
    ].join('\n')

    const result = parseGuestCSV(csv)
    expect(result.guests).toHaveLength(1)
    expect(result.warnings.some(w => /Expected 4 columns/.test(w))).toBe(true)
  })
})

describe('isActiveReservationStatus', () => {
  it('treats missing/empty status as active (legacy / non-Planyo CSV)', () => {
    expect(isActiveReservationStatus(undefined)).toBe(true)
    expect(isActiveReservationStatus(null)).toBe(true)
    expect(isActiveReservationStatus('')).toBe(true)
  })

  it('accepts any status containing "reserved" (case-insensitive, trimmed)', () => {
    expect(isActiveReservationStatus('Reserved')).toBe(true)
    expect(isActiveReservationStatus(' RESERVED ')).toBe(true)
    expect(isActiveReservationStatus('Reserved + Email address verified')).toBe(true)
    expect(
      isActiveReservationStatus('Reserved + Email address verified + confirmed')
    ).toBe(true)
    expect(isActiveReservationStatus('Reserved (rebooked)')).toBe(true)
  })

  it('rejects cancellations even when "reserved" is also present', () => {
    // "cancel" takes precedence over "reserved" so a hybrid status
    // like "Reserved → Cancelled" is treated as a cancellation.
    expect(isActiveReservationStatus('Cancelled')).toBe(false)
    expect(isActiveReservationStatus('Cancelled by admin')).toBe(false)
    expect(isActiveReservationStatus('Reserved → Cancelled')).toBe(false)
    expect(isActiveReservationStatus('Reservation cancelled')).toBe(false)
  })

  it('rejects OTHER statuses (no "reserved", no "cancel")', () => {
    expect(isActiveReservationStatus('Not completed')).toBe(false)
    expect(isActiveReservationStatus('Pending payment')).toBe(false)
    expect(isActiveReservationStatus('Added to waiting list')).toBe(false)
  })
})

describe('isCancelledStatus', () => {
  it('returns false for missing status', () => {
    expect(isCancelledStatus(undefined)).toBe(false)
    expect(isCancelledStatus(null)).toBe(false)
    expect(isCancelledStatus('')).toBe(false)
  })

  it('matches the substring "cancel" case-insensitively', () => {
    expect(isCancelledStatus('Cancelled')).toBe(true)
    expect(isCancelledStatus('cancelled')).toBe(true)
    expect(isCancelledStatus('CANCELLATION REQUESTED')).toBe(true)
    expect(isCancelledStatus('Cancelled by admin')).toBe(true)
  })

  it('does not match other non-active statuses', () => {
    expect(isCancelledStatus('Reserved')).toBe(false)
    expect(isCancelledStatus('Not completed')).toBe(false)
    expect(isCancelledStatus('Pending')).toBe(false)
  })

  it('active and cancelled are mutually exclusive on real Planyo statuses', () => {
    const samples = [
      'Reserved',
      'Reserved + Email address verified',
      'Reserved + Email address verified + confirmed',
      'Cancelled',
      'Cancelled by admin',
      'Not completed',
      'Added to waiting list',
    ]
    for (const s of samples) {
      const active = isActiveReservationStatus(s)
      const cancelled = isCancelledStatus(s)
      expect(active && cancelled).toBe(false)
    }
  })
})
